version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      WATCHPACK_POLLING: "true"
    command: npm run dev

  storybook:
    build:
      context: .
    ports:
      - "6006:6006"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      WATCHPACK_POLLING: "true"
    command: npm run storybook
