version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      WATCHPACK_POLLING: "true" # ホットリロードのための環境変数
    command: sh -c "npm run dev & npm run storybook"
